---
title: "Extract_locality"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Extract_locality}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rgeomex)
```


```{r example, dpi= 300}
library(magrittr)
library(sf)
loc_acapulco <-  rgeomex::loc_inegi19_mx %>%
    sf::st_make_valid() |>
        dplyr::filter(NOMGEO %in% c(similiars::find_most_similar_string("Acapulco de Juarez", unique(NOMGEO))) &
                          AMBITO %in% c("Urbana"))
plot(sf::st_geometry(loc_acapulco))

y <- rgeomex::AGEB_inegi_2019_a |>
    sf::st_make_valid()
ageb_acapulco <- y[loc_acapulco,]
head(ageb_acapulco)
ggplot2::ggplot()+
  ggplot2::geom_sf(data = ageb_acapulco,
                   fill = "gray80",
                   col = "white",
                   lwd = 0.1) +
  ggplot2::theme_void() +
  ggplot2::geom_sf(data = loc_acapulco,
                   fill = NA,
                   col = "black",
                   lwd = .5)

blocks_acapulco <- rbind(rgeomex::blocks_ine20_mx_a,
                         rgeomex::blocks_ine20_mx_b) |>
    sf::st_make_valid()

blocks_acapulco <- blocks_acapulco[loc_acapulco,]
head(blocks_acapulco)

ggplot2::ggplot()+
  ggplot2::geom_sf(data = blocks_acapulco,
                   fill = "gray80",
                   col = "white",
                   lwd = 0.1) +
  ggplot2::theme_void() +
  ggplot2::geom_sf(data = loc_acapulco,
                   fill = NA,
                   col = "black",
                   lwd = .5)

```
